### PR TITLE
adding piccolo

### PR DESCRIPTION
**Pull request by dantownsend**
Piccolo is an async ORM and query builder. It's stable and has a good feature set.

https://github.com/piccolo-orm/piccolo

There's a companion project which contains ASGI middleware, and utilities for building FastAPI endpoints really quickly, based off Piccolo models:

https://github.com/piccolo-orm/piccolo_api

It also has a nice admin GUI, which is an ASGI app, so is really easy to mount inside your FastAPI application:

https://github.com/piccolo-orm/piccolo_admin

### CODE REVIEW

**Comment by dantownsend** [comment]
The pull request is failing because some pre-existing Medium links are broken - should I fix these?

**Comment by mjhea0** [comment]
@dantownsend no, I can update those. Thanks!

**Comment by mjhea0** [comment]
@dantownsend I need to to a bit of research on Piccolo before I merge this since I've never used it before. There are quite a few async ORMs out there. Curious - why did you decide to build another?

**Comment by dantownsend** [comment]
@mjhea0 Yeah, it's actually a pretty old project - I think it started in 2018.

It's not as well known as some of the others, but I'm trying to get the word out more.

I guess the one you use is down to personal preference. The Piccolo syntax is very close to SQL, and uses type annotations everywhere, so works well with modern editors like VSCode.

Feature wise, Piccolo has an admin, migrations, authentication etc so can be used for building production ready apps.

I like the ‘playground’ too. It’s basically an iPython shell with a SQLite database and pre-defined schema, which is a nice little sandbox for learning Piccolo’s query syntax without having to setup any databases first.

Thanks for taking the time to look at it.

**Pull request merged**
