### PR TITLE
Add Dash-FastAPI-Admin

### PR DESCRIPTION
**Pull request by insistence**

### CODE REVIEW

**Review by icehongssii — CHANGES_REQUESTED** [review]
According to the [contribution guide](https://github.com/mjhea0/awesome-fastapi/blob/main/contributing.md), I think you need to put if at the end of the section!

**Comment by mjhea0** [comment]
Thanks for re-submitting the PR.

That section is in alphabetical order. Please update.

**Comment by insistence** [comment]
> Thanks for re-submitting the PR.
> 
> That section is in alphabetical order. Please update.

Thank you for your reply. My commit are arranged in alphabetical order.

> Thanks for re-submitting the PR.
> 
> That section is in alphabetical order. Please update.

Thank you for your reply. My commit are arranged in alphabetical order.

**Comment by insistence** [comment]
> Thanks for re-submitting the PR.
> 
> That section is in alphabetical order. Please update.

Thank you for your reply. My commit are arranged in alphabetical order.

**Pull request closed without merging**
