### PR TITLE
Add fastapi-mvc-template

### PR DESCRIPTION
**Pull request by rszamszur**
Few reasons for your discretion why maybe to add yet another template:

- The template utilizes WSGI + ASGI (Gunicorn with Uvicorn Workers) combination for the best performance possible.
- It is structured in MVC architectural pattern to help developers who don't know FastAPI yet but are familiar with MVC to get up to speed quickly.
- I've done my best to write this template in the most readable and Pythonic way (The Zen of Python) possible. Including docstrings and some clarifying comments here and there.
- Base utilities for Redis and aiohttp clients.
- Pipeline with build and tests (static checks, unit tests, coverage, and a placeholder for integration tests). Unit tests included :)
- Helm chart for deploying in Kubernetes cluster.
- Lastly, reproducible development environment with a script for bootstrapping local Minkube cluster with High Availability Redis cluster deployed using [spotathome/redis-operator](https://github.com/spotahome/redis-operator).

For future development, I'm planning to add features like:

- Project generator
- Multiple databases support
- Implementations for OAuth and JWT

### CODE REVIEW

**Comment by mjhea0** [comment]
This project looks great. However, I'm only going to accept projects that are at least a year old and are consistently being updated. Please open this PR again in July 2022.

**Comment by Kludex** [comment]
What about unmaintained projects? (I think the subject is related)

**Comment by mjhea0** [comment]
I agree, @Kludex. Can you open an issue with the list of projects that are unmaintained that you think should be removed?

**Comment by Kludex** [comment]
I don't have an opinion on that... I mean, I just did an innocent question.

I'm asking about the strategy you want to follow:
- Should we set a flag on the line to mark that it's unmaintained?
- Should we open PRs automatically to evaluate the state of the project once the project is unmaintained after X months?
- Define what is "unmaintained" for us. What does it mean to be unmaintained? A year without any update on the repository, or a year without any commit?
- Not act at all. Remove only if a PR is received stating the reasons of the removal.

**Comment by mjhea0** [comment]
https://github.com/mjhea0/awesome-fastapi/issues/109

**Pull request closed without merging**
