### PR TITLE
Added Deta Base

### PR DESCRIPTION
**Pull request by fillerInk**

### CODE REVIEW

**Comment by Kludex** [comment]
@fillerInk Could you explain why you think your MR suits here?

**Comment by mjhea0** [comment]
yeah, https://deta.sh is not just an unstructured db. it looks to be a full PaaS/serverless like solution like Zeit / https://vercel.com/.

**Comment by fillerInk** [comment]
@Kludex I believe deta will be useful for people building with fastapi

@mjhea0 Shall I add it under the serverless section then?

**Comment by mjhea0** [comment]
Not sure yet. I've never heard of deta before. Could you accompany it with a basic tutorial on using it with FastAPI?

**Comment by fillerInk** [comment]
https://dev.to/athulcajay/fastapi-deta-ni5

Please do go through this blog post to see if its fine.

Deta is a relatively new startup that was founded last year. We are still working on getting it to developers

**Comment by Kludex** [comment]
I think having https://dev.to/athulcajay/fastapi-deta-ni5 in the tutorial section it would be nice. But I'm still not convinced about having the Deta in the `other tools` yet... As you see, the tools listed there are related somehow with FastAPI. Don't you agree?

**Comment by fillerInk** [comment]
Yes, I agree with adding it to other tools. 
But I still think it makes sense to add it along with the serverless tools (which I admit is a mistake from my part for not adding it there initially)
What do you think?

**Comment by abdelhai** [comment]
Hi, #25 should suffice. Thanks all!

**Pull request closed without merging**
