### PR TITLE
add mangum

### PR DESCRIPTION
**Pull request by fkromer**

### CODE REVIEW

**Comment by mjhea0** [comment]
@fkromer I think this would be a better fit under the frameworks. It looks similar to Zappa or Chalice, right?

**Comment by fkromer** [comment]
@mjhea0 It is no framework. Probably it would best fit under compute cause it's related to AWS Lambda.

**Comment by mjhea0** [comment]
So, Zappa, Chalice, and Serverless Framework are essentially glue that binds together your route handlers with API Gateway and AWS Lambda. That's what Magnum does too, correct?

**Comment by mjhea0** [comment]
I'm going to lump it under frameworks for now. I could change that label to "Wrappers" or "Adapters".

**Pull request merged**
