### PR TITLE
Add the MultiPy docker images

### PR DESCRIPTION
**Pull request by tedivm**
The MultiPy image project grew out of a pull request to the fastapi uvicorn/gunicorn containers. The images are directly compatible with the FastAPI images with one major improvement- they are multiarchetecture/multiplatform so they can easily be used to create base iamges that can run on ARM (m1, gravitron) or AMD (intel, amd) systems.

### CODE REVIEW

**Comment by mjhea0** [comment]
Thanks for the PR. Let me think on this one since the images are more general and less FastAPI-specific.

**Comment by tedivm** [comment]
They formed out of two PRs ([fast-api-docker](https://github.com/tiangolo/uvicorn-gunicorn-fastapi-docker/pull/118) and [gunicorn](https://github.com/tiangolo/uvicorn-gunicorn-docker/pull/93)) on the FastAPI images that attempted to make those images work on multiple architectures. Most of the users come from that FastAPI ticket right now, which is why I thought they'd be relevant.

**Comment by mjhea0** [comment]
I'm going to pass on this for now. The list is starting to bloat already anyway.

**Comment by tedivm** [comment]
Seems kind of weird that you're leaving a bunch of broken and unmaintained projects while rejecting ones that work, but it's your list.

**Pull request closed without merging**
