### PR TITLE
Add Pyctuator

### PR DESCRIPTION
**Pull request by MatanRubin**
Pyctuator is a tool for monitoring and controlling FastAPI applications
using Spring Boot Admin's web UI.
It allows setting the application's log level in real time, seeing
metrics, checking DB health status, tracking various metrics, and much
more.

### CODE REVIEW

**Comment by mjhea0** [comment]
I don't really understand this. Why would you want to use a Spring Boot app to monitor your Python projects? This seems odd.

**Comment by MatanRubin** [comment]
Hi @mjhea0, thanks for the feedback. Take a look at the Why section in [Pyctuator's README,](https://github.com/SolarEdgeTech/pyctuator#why) it explains it well. 

In a nutshell - in many situations you already have Spring Boot Admin running and monitoring a bunch of Java microservices, and you want to interact with your Python microservices in a similar fashion, and benefit from all the goodies that Spring Boot Admin offers.

I'd even argue that Pyctuator is so powerful that it justifies spinning up a Spring Boot Admin just to use it with your FastAPI app.

TBH, I don't know of any other tool that offers what Pyctuator+Spring Boot Admin offers for FastAPI. If you're familiar with anything like it I'd love to hear more about it!

**Comment by mjhea0** [comment]
I see. 

I guess maybe we could add a APM/monitoring section, adding hosted solutions like airbrake, sentry, etc. along with open sources tools like Pyctuator and https://github.com/sensu/sensu-go. 

Let me think about this.

**Comment by MatanRubin** [comment]
@mjhea0 , I'm not sure I understand the comparison. AFAIK, the tools you mentioned are general APM/Monitoring tools that are not specific to FastAPI. Pyctuator, on the other hand, was developed specifically for FastAPI, with only a single line of code required for integrating the two.

There's a complete FastAPI+Pyctuator example [here](https://github.com/SolarEdgeTech/pyctuator/tree/master/examples/FastAPI), maybe that would clear things up.

**Comment by MatanRubin** [comment]
Hi @mjhea0 , can you explain why this was closed and not merged? 

Did you take a look at Pyctuator? It is a very valuable tool for FastAPI users, and I don't know of any other tool which offers this functionality...

**Comment by mjhea0** [comment]
I still don't think it belongs here. You are more than welcome to fork this repo and add it to your own awesome list if you'd like.

**Comment by MatanRubin** [comment]
Very disappointed for this to be closed without a concrete explanation. 

I even noticed that someone else tried to add it before me a few months back (see https://github.com/mjhea0/awesome-fastapi/pull/62), meaning I'm not the only one who thinks it does belong here (you know, for being a truly awesome tool for FastAPI users).

**Pull request closed without merging**
